CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ── Users ────────────────────────────────────────────────────────
CREATE TABLE users
(
    id            integer GENERATED BY DEFAULT AS IDENTITY,
    created_at    timestamp(6) NOT NULL,
    email         varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    username      varchar(255) NOT NULL,

    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT uk_users_username
        UNIQUE (username)
);


-- ── User Profiles ────────────────────────────────────────────────
CREATE TABLE user_profiles
(
    user_id        integer NOT NULL,
    activity_level varchar(255) NOT NULL,
    created_at     timestamp(6) NOT NULL,
    date_of_birth  date NOT NULL,
    first_name     varchar(255) NOT NULL,
    gender         varchar(255) NOT NULL,
    goal_type      varchar(255) NOT NULL,
    goal_weight    double precision,
    height         double precision NOT NULL,
    last_name      varchar(255) NOT NULL,
    weekly_goal    double precision,

    CONSTRAINT pk_user_profiles
        PRIMARY KEY (user_id),

    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_user_profiles_activity_level
        CHECK (
            activity_level IN (
                               'SEDENTARY',
                               'LIGHT',
                               'MODERATE',
                               'HEAVY',
                               'ATHLETE'
                )
            ),

    CONSTRAINT chk_user_profiles_gender
        CHECK (
            gender IN (
                       'MALE',
                       'FEMALE'
                )
            ),

    CONSTRAINT chk_user_profiles_goal_type
        CHECK (
            goal_type IN (
                          'LOSE_WEIGHT',
                          'MAINTAIN_WEIGHT',
                          'GAIN_WEIGHT'
                )
            )
);


-- ── Weight Logs ──────────────────────────────────────────────────
CREATE TABLE weight_logs
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) NOT NULL,
    logged_at  timestamp(6) NOT NULL,
    updated_at timestamp(6),
    weight     double precision NOT NULL,
    user_id    integer NOT NULL,

    CONSTRAINT pk_weight_logs
        PRIMARY KEY (id),

    CONSTRAINT fk_weight_logs_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);


-- ── Foods ────────────────────────────────────────────────────────
CREATE TABLE foods
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY,
    brand                varchar(255),
    calories_per_serving double precision NOT NULL,
    carbs_per_serving    double precision NOT NULL,
    created_at           timestamp(6) NOT NULL,
    fat_per_serving      double precision NOT NULL,
    name                 varchar(255) NOT NULL,
    protein_per_serving  double precision NOT NULL,
    serving_size_grams   double precision NOT NULL,
    updated_at           timestamp(6),
    created_by_user_id   integer,

    CONSTRAINT pk_foods
        PRIMARY KEY (id),

    CONSTRAINT fk_foods_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON DELETE SET NULL
);


-- ── Meals ────────────────────────────────────────────────────────
CREATE TABLE meals
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) NOT NULL,
    meal_date  date,
    name       varchar(255) NOT NULL,
    updated_at timestamp(6),
    user_id    integer NOT NULL,
    kind       varchar(255) NOT NULL,

    CONSTRAINT pk_meals
        PRIMARY KEY (id),

    CONSTRAINT fk_meals_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);


-- ── Meal Items ───────────────────────────────────────────────────
CREATE TABLE meal_items
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY,
    brand                varchar(255),
    calories_per_serving double precision NOT NULL,
    carbs_per_serving    double precision NOT NULL,
    created_at           timestamp(6) NOT NULL,
    fat_per_serving      double precision NOT NULL,
    food_name            varchar(255) NOT NULL,
    protein_per_serving  double precision NOT NULL,
    quantity_grams       double precision NOT NULL,
    serving_size_grams   double precision NOT NULL,
    updated_at           timestamp(6),
    food_id              integer,
    meal_id              integer NOT NULL,

    CONSTRAINT pk_meal_items
        PRIMARY KEY (id),

    CONSTRAINT fk_meal_items_food
        FOREIGN KEY (food_id)
            REFERENCES foods (id)
            ON DELETE SET NULL,

    CONSTRAINT fk_meal_items_meal
        FOREIGN KEY (meal_id)
            REFERENCES meals (id)
            ON DELETE CASCADE
);


-- ── Foods Indexes ────────────────────────────────────────────────
CREATE INDEX idx_foods_created_by_user_name
    ON foods (created_by_user_id, name);

CREATE INDEX idx_foods_name
    ON foods (name);

CREATE INDEX idx_foods_name_trgm
    ON foods USING gin (lower(name) gin_trgm_ops);


-- ── Meals Indexes ────────────────────────────────────────────────
CREATE INDEX idx_meals_name_trgm
    ON meals USING gin (lower(name) gin_trgm_ops);

CREATE INDEX idx_meals_user_date_kind_id
    ON meals (user_id, meal_date, kind, id);

CREATE INDEX idx_meals_user_kind_name
    ON meals (user_id, kind, name);


-- ── Meal Item Indexes ────────────────────────────────────────────
CREATE INDEX idx_meal_items_meal_id_id
    ON meal_items (meal_id, id);