CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ── Users ────────────────────────────────────────────────────────
CREATE TABLE users
(
    id            integer GENERATED BY DEFAULT AS IDENTITY,
    created_at    timestamptz(6) NOT NULL,
    email         varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    username      varchar(255) NOT NULL,

    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT uk_users_username
        UNIQUE (username)
);


-- ── User Profiles ────────────────────────────────────────────────
CREATE TABLE user_profiles
(
    user_id       integer NOT NULL,
    created_at    timestamptz(6) NOT NULL,
    updated_at    timestamptz(6),
    date_of_birth date NOT NULL,
    first_name    varchar(255) NOT NULL,
    gender        varchar(255) NOT NULL,
    height        double precision NOT NULL,
    last_name     varchar(255) NOT NULL,

    CONSTRAINT pk_user_profiles
        PRIMARY KEY (user_id),

    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_user_profiles_gender
        CHECK (
            gender IN (
                'MALE',
                'FEMALE'
            )
        )
);


-- ── Weight Logs ──────────────────────────────────────────────────
CREATE TABLE weight_logs
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz(6) NOT NULL,
    logged_at  timestamptz(6) NOT NULL,
    updated_at timestamptz(6),
    weight     double precision NOT NULL,
    user_id    integer NOT NULL,

    CONSTRAINT pk_weight_logs
        PRIMARY KEY (id),

    CONSTRAINT fk_weight_logs_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_weight_logs_weight
        CHECK (weight > 0)
);


-- ── Foods ────────────────────────────────────────────────────────
CREATE TABLE foods
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY,
    brand                varchar(255),
    calories_per_serving double precision NOT NULL,
    carbs_per_serving    double precision NOT NULL,
    created_at           timestamptz(6) NOT NULL,
    fat_per_serving      double precision NOT NULL,
    name                 varchar(255) NOT NULL,
    protein_per_serving  double precision NOT NULL,
    serving_size_grams   double precision NOT NULL,
    updated_at           timestamptz(6),
    created_by_user_id   integer,

    CONSTRAINT pk_foods
        PRIMARY KEY (id),

    CONSTRAINT fk_foods_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON DELETE SET NULL
);


-- ── Meals ────────────────────────────────────────────────────────
CREATE TABLE meals
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz(6) NOT NULL,
    meal_date  date,
    name       varchar(255) NOT NULL,
    updated_at timestamptz(6),
    user_id    integer NOT NULL,
    kind       varchar(255) NOT NULL,

    CONSTRAINT pk_meals
        PRIMARY KEY (id),

    CONSTRAINT fk_meals_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);


-- ── Meal Items ───────────────────────────────────────────────────
CREATE TABLE meal_items
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY,
    brand                varchar(255),
    calories_per_serving double precision NOT NULL,
    carbs_per_serving    double precision NOT NULL,
    created_at           timestamptz(6) NOT NULL,
    fat_per_serving      double precision NOT NULL,
    food_name            varchar(255) NOT NULL,
    protein_per_serving  double precision NOT NULL,
    quantity_grams       double precision NOT NULL,
    serving_size_grams   double precision NOT NULL,
    updated_at           timestamptz(6),
    food_id              integer,
    meal_id              integer NOT NULL,

    CONSTRAINT pk_meal_items
        PRIMARY KEY (id),

    CONSTRAINT fk_meal_items_food
        FOREIGN KEY (food_id)
            REFERENCES foods (id)
            ON DELETE SET NULL,

    CONSTRAINT fk_meal_items_meal
        FOREIGN KEY (meal_id)
            REFERENCES meals (id)
            ON DELETE CASCADE
);


-- ── Nutrition Goals ──────────────────────────────────────────────
CREATE TABLE nutrition_goals
(
    id                    integer GENERATED BY DEFAULT AS IDENTITY,
    user_id               integer NOT NULL,
    activity_level        varchar(255) NOT NULL,
    goal_type             varchar(255) NOT NULL,
    goal_weight           double precision,
    weekly_goal           double precision,
    target_calories       integer NOT NULL,
    target_protein        double precision NOT NULL,
    target_carbs          double precision NOT NULL,
    target_fat            double precision NOT NULL,
    start_date            date NOT NULL,
    end_date              date,
    progress_start_weight double precision NOT NULL,
    progress_started_at   timestamptz(6) NOT NULL,
    created_at            timestamptz(6) NOT NULL,
    updated_at            timestamptz(6),

    CONSTRAINT pk_nutrition_goals
        PRIMARY KEY (id),

    CONSTRAINT fk_nutrition_goals_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_nutrition_goals_activity_level
        CHECK (
            activity_level IN (
                'SEDENTARY',
                'LIGHT',
                'MODERATE',
                'HEAVY',
                'ATHLETE'
            )
        ),

    CONSTRAINT chk_nutrition_goals_goal_type
        CHECK (
            goal_type IN (
                'LOSE_WEIGHT',
                'MAINTAIN_WEIGHT',
                'GAIN_WEIGHT'
            )
        ),

    CONSTRAINT chk_nutrition_goals_goal_weight
        CHECK (
            goal_weight IS NULL
                OR goal_weight > 0
        ),

    CONSTRAINT chk_nutrition_goals_weekly_goal
        CHECK (
            weekly_goal IS NULL
                OR weekly_goal > 0
        ),

    CONSTRAINT chk_nutrition_goals_targets
        CHECK (
            target_calories > 0
                AND target_protein >= 0
                AND target_carbs >= 0
                AND target_fat >= 0
        ),

    CONSTRAINT chk_nutrition_goals_date_range
        CHECK (
            end_date IS NULL
                OR end_date >= start_date
        ),

    CONSTRAINT chk_nutrition_goals_progress_start_weight
        CHECK (progress_start_weight > 0)
);


-- ── Body Measurement Logs ────────────────────────────────────────
CREATE TABLE body_measurement_logs
(
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    user_id    integer NOT NULL,
    waist      double precision NOT NULL,
    neck       double precision NOT NULL,
    hip        double precision,
    logged_at  timestamptz(6) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    updated_at timestamptz(6),

    CONSTRAINT pk_body_measurement_logs
        PRIMARY KEY (id),

    CONSTRAINT fk_body_measurement_logs_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_body_measurement_logs_neck
        CHECK (neck > 0),

    CONSTRAINT chk_body_measurement_logs_waist
        CHECK (waist > 0),

    CONSTRAINT chk_body_measurement_logs_hip
        CHECK (
            hip IS NULL
                OR hip > 0
        )
);


-- ── Foods Indexes ────────────────────────────────────────────────
CREATE INDEX idx_foods_created_by_user_name
    ON foods (created_by_user_id, name);

CREATE INDEX idx_foods_name
    ON foods (name);

CREATE INDEX idx_foods_name_trgm
    ON foods USING gin (lower(name) gin_trgm_ops);


-- ── Meals Indexes ────────────────────────────────────────────────
CREATE INDEX idx_meals_name_trgm
    ON meals USING gin (lower(name) gin_trgm_ops);

CREATE INDEX idx_meals_user_date_kind_id
    ON meals (user_id, meal_date, kind, id);

CREATE INDEX idx_meals_user_kind_name
    ON meals (user_id, kind, name);

CREATE UNIQUE INDEX uk_meals_daily_user_date_name
    ON meals (user_id, meal_date, name)
    WHERE kind = 'DAILY';


-- ── Meal Item Indexes ────────────────────────────────────────────
CREATE INDEX idx_meal_items_meal_id_id
    ON meal_items (meal_id, id);


-- ── Nutrition Goal Indexes ──────────────────────────────────────
CREATE UNIQUE INDEX uk_nutrition_goals_user_start_date
    ON nutrition_goals (user_id, start_date);

CREATE UNIQUE INDEX uk_nutrition_goals_active_user
    ON nutrition_goals (user_id)
    WHERE end_date IS NULL;


-- ── Weight Log Indexes ──────────────────────────────────────────
CREATE INDEX idx_weight_logs_user_logged_at_id
    ON weight_logs (user_id, logged_at DESC, id DESC);

CREATE UNIQUE INDEX uk_weight_logs_user_logged_date
    ON weight_logs (
        user_id,
        ((logged_at AT TIME ZONE 'Europe/Belgrade')::date)
    );


-- ── Body Measurement Log Indexes ────────────────────────────────
CREATE INDEX idx_body_measurement_logs_user_logged_at_id
    ON body_measurement_logs (user_id, logged_at DESC, id DESC);

CREATE UNIQUE INDEX uk_body_measurement_logs_user_logged_date
    ON body_measurement_logs (
        user_id,
        ((logged_at AT TIME ZONE 'Europe/Belgrade')::date)
    );
