-- ── Nutrition Goals ────────────────────────────────────────────────
CREATE TABLE nutrition_goals
(
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL,

    activity_level  varchar(255) NOT NULL,
    goal_type       varchar(255) NOT NULL,
    goal_weight     double precision,
    weekly_goal     double precision,

    target_calories integer NOT NULL,
    target_protein  double precision NOT NULL,
    target_carbs    double precision NOT NULL,
    target_fat      double precision NOT NULL,

    start_date      date NOT NULL,
    end_date        date,

    created_at      timestamp(6) NOT NULL,
    updated_at      timestamp(6),

    CONSTRAINT fk_nutrition_goals_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_nutrition_goals_activity_level
        CHECK (
            activity_level IN (
                               'SEDENTARY',
                               'LIGHT',
                               'MODERATE',
                               'HEAVY',
                               'ATHLETE'
                )
            ),

    CONSTRAINT chk_nutrition_goals_goal_type
        CHECK (
            goal_type IN (
                          'LOSE_WEIGHT',
                          'MAINTAIN_WEIGHT',
                          'GAIN_WEIGHT'
                )
            ),

    CONSTRAINT chk_nutrition_goals_goal_weight
        CHECK (
            goal_weight IS NULL
                OR goal_weight > 0
            ),

    CONSTRAINT chk_nutrition_goals_weekly_goal
        CHECK (
            weekly_goal IS NULL
                OR weekly_goal > 0
            ),

    CONSTRAINT chk_nutrition_goals_targets
        CHECK (
            target_calories > 0
                AND target_protein >= 0
                AND target_carbs >= 0
                AND target_fat >= 0
            ),

    CONSTRAINT chk_nutrition_goals_date_range
        CHECK (
            end_date IS NULL
                OR end_date >= start_date
            )
);

-- ── Indexes ────────────────────────────────────────────────
CREATE INDEX idx_nutrition_goals_user_start_date
    ON nutrition_goals (user_id, start_date);

CREATE UNIQUE INDEX uk_nutrition_goals_active_user
    ON nutrition_goals (user_id)
    WHERE end_date IS NULL;

-- ── User Profiles Change ────────────────────────────────────────────────
ALTER TABLE user_profiles
DROP COLUMN activity_level,
    DROP COLUMN goal_type,
    DROP COLUMN goal_weight,
    DROP COLUMN weekly_goal;