-- ── Body Measurement Logs ────────────────────────────────────────────────
CREATE TABLE body_measurement_logs
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL,

    waist      double precision NOT NULL,
    neck       double precision NOT NULL,
    hip        double precision,

    logged_at  timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),

    CONSTRAINT fk_body_measurement_logs_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_body_measurement_logs_neck
        CHECK (neck > 0),

    CONSTRAINT chk_body_measurement_logs_waist
        CHECK (waist > 0),

    CONSTRAINT chk_body_measurement_logs_hip
        CHECK (
            hip IS NULL
                OR hip > 0
            )
);

-- ── Indexes ────────────────────────────────────────────────
CREATE INDEX idx_body_measurement_logs_user_logged_at
    ON body_measurement_logs (user_id, logged_at DESC);