spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Server
server.address=127.0.0.1

# Time Zone
app.time-zone=Europe/Belgrade

# Flyway
spring.flyway.enabled=true